[project]
name = 'Nanotechnology-Research-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.nanotech-nft]
path = 'contracts/nanotech-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-proposal]
path = 'contracts/research-proposal.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
